### PR TITLE
Feature - Help modal scroll

### PR DESCRIPTION
**Pull request by AliNisarAhmed**
- [x] Have you [followed the contributing guidelines](https://github.com/smallhadroncollider/taskell/blob/master/CONTRIBUTING.md)?
- [x] Are you working/merging into `develop`?
- [x] Do all tests pass?

If appropriate:

- [ ] Have you added new tests for additional functionality?

---

### CODE REVIEW

**Comment by AliNisarAhmed** [comment]
@smallhadroncollider Found the unused import, removed. 

Also, do you want me to add tests for the help modal scroll functionality?

**Comment by AliNisarAhmed** [comment]
Changing to draft as I forgot to fix the up/down reverse scroll in help modal.

**Comment by smallhadroncollider** [comment]
I'm still getting:

```
/Volumes/Projects/mark/taskell/src/Taskell/UI/Draw/Modal/Help.hs:12:1-26:
warning: [-Wunused-imports]
    The import of ‘Control.Lens’ is redundant
   |
12 | import Control.Lens ((^.))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
/Volumes/Projects/mark/taskell/src/Taskell/UI/Draw/Modal/Help.hs:14:1-40:
warning: [-Wunused-imports]
    The import of ‘Taskell.Events.State.Types’ is redundant
   |
14 | import Taskell.Events.State.Types (mode)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Volumes/Projects/mark/taskell/src/Taskell/UI/Draw/Modal/Help.hs:18:1-83:
warning: [-Wunused-imports]
    The import of ‘DrawState(dsState)’
    from module ‘Taskell.UI.Draw.Types’ is redundant
   |
18 | import Taskell.UI.Draw.Types (DrawState(dsBindings, dsState),
ModalWidget, TWidget)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Volumes/Projects/mark/taskell/src/Taskell/Events/State/Modal/Help.hs:4:1-37: warning: [-Wunused-imports]
    The import of ‘&, ^.’ from module ‘Control.Lens’ is redundant
  |
4 | import Control.Lens ((&), (.~), (^.))
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Volumes/Projects/mark/taskell/src/Taskell/Events/State/Modal/Help.hs:(6,1)-(12,3): warning: [-Wunused-imports]
    The import of ‘Detail, DetailItem, DetailMode’
    from module ‘Taskell.Events.State.Types.Mode’ is redundant
  |
6 | import Taskell.Events.State.Types.Mode
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

```

**Comment by smallhadroncollider** [comment]
If you can think of some useful tests to add then go for it! But I don't think UI stuff is tested elsewhere, so I wouldn't worry about it. I'll look into UI testing for 2.0.

**Comment by AliNisarAhmed** [comment]
Removed unused imports, fixed help modal scroll direction, all other buttons except Up/Down/Next/Previous close the Help modal as before.

**Comment by smallhadroncollider** [comment]
@AliNisarAhmed Amazing - thanks!

Hopefully have time to look at this in the afternoon - but quite busy today, so might not be until next week.

**Comment by smallhadroncollider** [comment]
Great work @AliNisarAhmed!

**Pull request merged**
