### PR TITLE
Pomodoro

### PR DESCRIPTION
**Pull request by machinedgod**
#35 

~~Use just for review.~~ Merge if good enough, complain if not and I'll fix what I need to :-)

### CODE REVIEW

**Comment by smallhadroncollider** [comment]
I will try and have a proper look at this next week. My son's got chicken pox and it's the week my wife and I both go back to work properly, so it's been a bit hectic!

**Comment by machinedgod** [comment]
Oh, sorry to hear that! Hope the kid gets better soon, and good luck with going back to work. No rush with review, I'll try and wrap up the work for you, so that you get a nice clean PR at least.

**Comment by smallhadroncollider** [comment]
Hello.

Sorry for delay, I was teaching all last week and didn't have a chance to have a proper look.

Definitely very promising so far.

A few things:

1) Rather than showing "No pomodoro running." maybe just use an `emptyWidget` (from `Brick`). Then if you're not interested in pomodoro you need never know it's there. I'm thinking of maybe adding the file name at the top of taskell, in which case having the timer right aligned at the top might work quite well.

2) Would be good to zero-pad numbers. e.g. `05.00` instead of `5.0`

I'll try and do a code review later this week. Most likely on Thursday afternoon when I get my next child-at-nursery-but-not-at-work session.

**Comment by machinedgod** [comment]
Hey! Thanks for the quick review.
I'm handling one client atm so I'm a bit busy for the next few days, but I'll fix all the points quite probably by Friday.

**Comment by smallhadroncollider** [comment]
No worries.

In the `develop` branch I've added a status bar along the bottom. Currently it shows the file name, mode, and position. Might also be a good place for the timer to live? Perhaps the background could change colour instead of the timer text.

**Comment by smallhadroncollider** [comment]
No worries.

I've made quite a few changes in the last few weeks, hopefully it doesn't make it too grim to merge.

**Comment by smallhadroncollider** [comment]
Sorry, I'm going to close this for now. There have been so many changes to the main branch that I'm not sure merging it would be the best way forward.

**Pull request closed without merging**
